medication_data = [{"id": 327096008,
                    "full_name": "Tacrolimus 1mg capsules",
                    "short_name": "Tacrolimus",
                    "cautionary_text": "Avoid excessive exposure to UV light including sunlight.",
                    "icon_name": "/home/sam/Git/MediPi/MediPiConcentrator/config/icons/capsule.png",
                    "dose_unit_id": 1
                    },
                   {"id": 8077011000001100,
                        "full_name": "Mycophenolic acid 360mg gastro-resistant tablets",
                        "short_name": "Mycophenolic acid",
                        "cautionary_text": "Avoid excessive exposure to UV light including sunlight.",
                        "icon_name": "/home/sam/Git/MediPi/MediPiConcentrator/config/icons/capsule.png",
                        "dose_unit_id": 0
                        },
                   {"id": 317544000,
                        "full_name": "Docusate 100mg capsules",
                        "short_name": "Docusate",
                        "cautionary_text": "Avoid excessive exposure to UV light including sunlight.",
                        "icon_name": "/home/sam/Git/MediPi/MediPiConcentrator/config/icons/capsule.png",
                        "dose_unit_id": 1
                        },
                   {"id": 8791311000001100,
                        "full_name": "Azathioprine 10mg capsules",
                        "short_name": "Azathioprine",
                        "cautionary_text": "Avoid excessive exposure to UV light including sunlight.",
                        "icon_name": "/home/sam/Git/MediPi/MediPiConcentrator/config/icons/capsule.png",
                        "dose_unit_id": 1
                        },
                   {"id": 418349006,
                        "full_name": "Prednisone 1mg tablets",
                        "short_name": "Prednisone",
                        "cautionary_text": "Avoid excessive exposure to UV light including sunlight.",
                        "icon_name": "/home/sam/Git/MediPi/MediPiConcentrator/config/icons/capsule.png",
                        "dose_unit_id": 0
                    },
                   {"id": 408155001,
                    "full_name": "Sirolimus 2mg tablets",
                    "short_name": "Sirolimus",
                    "cautionary_text": "Avoid excessive exposure to UV light including sunlight.",
                    "icon_name": "/home/sam/Git/MediPi/MediPiConcentrator/config/icons/capsule.png",
                    "dose_unit_id": 0
                    }]
